/**
 * Differential validation against the ORIGINAL desktop implementation.
 *
 * The fixtures in __fixtures__/desktop-oracle.json were generated by running
 * the original RFQ-Planner desktop app's pandas calculations (verbatim copies
 * of budget_controller / resource_controller / Role.get_ftes_for_month) over
 * 30 randomized projects — mixed fixed/variable allocations, overlapping and
 * out-of-range periods, zero rates, missing quotas, zero story points.
 *
 * Every number the TypeScript engine produces must match the original
 * implementation's output.
 */

import { describe, expect, it } from 'vitest'
import fixtures from './__fixtures__/desktop-oracle.json'
import type { Feature, Project, RateConfig } from '../types'
import {
  budgetPivots,
  buildBudgetRows,
  costProfitOverall,
  costProfitSummary,
  projectMonths,
  ticketAnalysis,
} from './engine'
import { emptyMoneyConfig, type MoneyConfig } from './types'

const LOCATIONS = ['BCC', 'HCC', 'MCC']
const LEVELS = ['PM/TL', 'FO', 'Principal', 'Senior', 'Standard', 'Junior']
const SIZES = ['small', 'medium', 'large']

interface Fixture {
  name: string
  project: {
    start_year: number
    start_month: number
    end_year: number
    end_month: number
    features: {
      name: string
      roles: {
        name: string
        location: string
        level: string
        ftes: number
        use_advanced_allocation: boolean
        allocations: { start_month: string; end_month: string; ftes: number }[]
      }[]
    }[]
  }
  money: {
    hourly_rates: Record<string, number>
    cost_rates: Record<string, Record<string, number>>
    hw_cost_per_hour: number
  }
  rates: {
    sp_to_hours: number
    risk_factor_pct: number
    ticket_story_points: Record<string, number>
    ticket_quotas: Record<string, Record<string, number>>
  }
  expected: {
    cost_profit_summary: Record<string, string | number>[]
    cost_profit_overall: Record<string, string | number>[]
    ticket_analysis: Record<string, string | number>[]
    budget_pivots: Record<string, { columns: string[]; rows: Record<string, string | number>[] }>
    resource_pivots: Record<string, { columns: string[]; rows: Record<string, string | number>[] }>
  }
}

function toProject(fx: Fixture): Project {
  let roleId = 1
  const features: Feature[] = fx.project.features.map((f, fi) => ({
    id: fi + 1,
    project_id: 1,
    name: f.name,
    roles: f.roles.map((r) => ({
      id: roleId++,
      feature_id: fi + 1,
      name: r.name,
      location: r.location,
      level: r.level,
      ftes: r.ftes,
      use_advanced_allocation: r.use_advanced_allocation,
      allocations: r.allocations.map((a, ai) => ({ id: ai + 1, ...a })),
    })),
  }))
  return {
    id: 1,
    name: fx.name,
    company: 'Oracle',
    start_year: fx.project.start_year,
    start_month: fx.project.start_month,
    end_year: fx.project.end_year,
    end_month: fx.project.end_month,
    status: 'draft',
    win_probability_pct: 50,
    lost_reason: null,
    base_project_id: null,
    is_winning_scenario: false,
    created_at: '',
    updated_at: '',
    features,
  }
}

function toMoney(fx: Fixture): MoneyConfig {
  return {
    ...emptyMoneyConfig(LOCATIONS, LEVELS, SIZES),
    hourly_rates: fx.money.hourly_rates,
    cost_rates: fx.money.cost_rates,
    hw_cost_per_hour: fx.money.hw_cost_per_hour,
  }
}

function toRates(fx: Fixture): RateConfig {
  return {
    sp_to_hours: fx.rates.sp_to_hours,
    risk_factor_pct: fx.rates.risk_factor_pct,
    ticket_story_points: fx.rates.ticket_story_points,
    ticket_quotas: fx.rates.ticket_quotas,
  }
}

const EXACT = 1e-6
// Original rounds ticket figures with Python's round() (banker's rounding);
// JS Math.round differs only exactly at .xx5 boundaries.
const ROUNDED = 0.011

function expectClose(actual: number, expected: number, tol: number, label: string) {
  expect(Math.abs(actual - expected), `${label}: ${actual} vs ${expected}`).toBeLessThanOrEqual(
    tol + Math.abs(expected) * 1e-9,
  )
}

function comparePivot(
  got: { columns: string[]; rows: Record<string, string | number>[] },
  expected: { columns: string[]; rows: Record<string, string | number>[] },
  label: string,
) {
  expect(got.columns, `${label} columns`).toEqual(expected.columns)
  const key = (r: Record<string, string | number>) =>
    `${r.Feature}|${r.Role}|${r.Location}|${r.Level}`
  const gotMap = new Map(got.rows.map((r) => [key(r), r]))
  const expMap = new Map(expected.rows.map((r) => [key(r), r]))
  expect([...gotMap.keys()].sort(), `${label} row set`).toEqual([...expMap.keys()].sort())
  for (const [k, er] of expMap) {
    const gr = gotMap.get(k)!
    for (const col of expected.columns) {
      const ev = er[col]
      if (typeof ev === 'number') {
        expectClose(Number(gr[col]), ev, EXACT, `${label} ${k} ${col}`)
      }
    }
  }
  // Data rows (before totals) must be in identical order to the original
  const dataOrder = (rows: Record<string, string | number>[]) =>
    rows.filter((r) => !String(r.Feature).startsWith('TOTAL')).map(key)
  expect(dataOrder(got.rows), `${label} row order`).toEqual(dataOrder(expected.rows))
}

describe('engine vs original desktop implementation (30 randomized fixtures)', () => {
  for (const fx of fixtures as unknown as Fixture[]) {
    it(fx.name, () => {
      const project = toProject(fx)
      const money = toMoney(fx)
      const rates = toRates(fx)
      const months = projectMonths(project)
      const rows = buildBudgetRows(project, money, months)

      // Cost-profit summary
      const summary = costProfitSummary(rows)
      expect(summary.length).toBe(fx.expected.cost_profit_summary.length)
      for (let i = 0; i < summary.length; i++) {
        const got = summary[i]
        const exp = fx.expected.cost_profit_summary[i]
        expect(`${got.year}|${got.location}`).toBe(`${exp.year}|${exp.location}`)
        for (const f of ['man_hours', 'cost', 'selling_price', 'hourly_cost',
                         'hourly_rate', 'profit', 'profit_pct'] as const) {
          expectClose(got[f], Number(exp[f]), EXACT, `summary[${i}].${f}`)
        }
      }

      // Overall rows
      const overall = costProfitOverall(summary)
      expect(overall.length).toBe(fx.expected.cost_profit_overall.length)
      for (let i = 0; i < overall.length; i++) {
        const got = overall[i]
        const exp = fx.expected.cost_profit_overall[i]
        expect(got.year).toBe(exp.year)
        for (const f of ['man_hours', 'cost', 'selling_price', 'hourly_cost',
                         'hourly_rate', 'profit', 'profit_pct'] as const) {
          expectClose(got[f], Number(exp[f]), EXACT, `overall[${i}].${f}`)
        }
      }

      // Ticket analysis
      const tickets = ticketAnalysis(rows, money, rates)
      expect(tickets.length).toBe(fx.expected.ticket_analysis.length)
      for (let i = 0; i < tickets.length; i++) {
        const got = tickets[i]
        const exp = fx.expected.ticket_analysis[i]
        expect(`${got.year}|${got.size}`).toBe(`${exp.year}|${exp.size}`)
        expectClose(got.story_points, Number(exp.story_points), EXACT, `tickets[${i}].sp`)
        expectClose(got.hours_per_ticket, Number(exp.hours_per_ticket), EXACT, `tickets[${i}].hpt`)
        for (const f of ['num_tickets', 'total_hours', 'hourly_rate', 'revenue'] as const) {
          expectClose(got[f], Number(exp[f]), ROUNDED, `tickets[${i}].${f}`)
        }
      }

      // Budget pivots (selling price)
      const pivots = budgetPivots(rows)
      const expectedYears = Object.keys(fx.expected.budget_pivots).sort()
      expect(pivots.map((p) => p.year)).toEqual(expectedYears)
      for (const pivot of pivots) {
        comparePivot(pivot, fx.expected.budget_pivots[pivot.year], `budget ${pivot.year}`)
      }
    })
  }
})
